site_name: Jotunheim
site_url: https://github.com/atreussoltani/atreussoltani.github.io
site_author: Abolfazl Soltani
site_description: My personal blog

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: blue
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: تم روشن
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: تم تیره
  language: fa
  font:
    text: Vazirmatn
    code: Source Code Pro
  logo: assets/images/terraform.png
  favicon: assets/images/terraform.png
  features:
    - navigation.tabs
    - content.code.copy

nav:
  - index.md
  - بلاگ:
      - blog/index.md

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: material/web
      link: https://atreussoltani.github.io
      name: وب‌سایت
    - icon: fontawesome/brands/github
      link: https://github.com/atreussoltani
      name: گیت‌هاب
    - icon: fontawesome/brands/telegram
      link: https://t.me/absoltani02
      name: تلگرام

plugins:
  - search
  - blog:
      categories_allowed:
        - Food
        - Travel
        - Personal
        - Experience

markdown_extensions:
  - admonition
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
