site_name: ترافورم
site_url: https://github.com/atreussoltani/atreussoltani.github.io
site_author: ابوالفضل سلطانی
site_description: آموزش ترافورم

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: blue
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: تم روشن
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: تم تیره
  language: fa
  font:
    text: Vazirmatn
    code: Source Code Pro
  logo: assets/images/terraform.png
  favicon: assets/images/sid.png
  features:
    - navigation.tabs
    - content.code.copy

nav:
  - index.md
  - intro.md
  - زیرسازی با کد: iac.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: material/web
      link: https://atreussoltani.github.io
      name: وب‌سایت
    - icon: fontawesome/brands/github
      link: https://github.com/atreussoltani
      name: گیت‌هاب
    - icon: fontawesome/brands/telegram
      link: https://t.me/absoltani02
      name: تلگرام

plugins: 
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - footnotes